### ISSUE TITLE
ignition config spec v2.1.0 official release?

### ISSUE THREAD

**Issue by s-urbaniak** [terraform-providers/terraform-provider-ignition#16]
The Ignition config spec v2.1.0 PR #8 landed. I was wondering when it will appear on https://releases.hashicorp.com/terraform-provider-ignition/ for general usage?

Thanks for any hints and the hard work to make it happen!

/cc @alexsomesan @sym3tri

**Comment by mcuadros** [comment]
Should be released this week. We need to agree the version number.

**Comment by s-urbaniak** [comment]
@mcuadros great, thanks for the heads-up!

**Comment by mcuadros** [comment]
https://github.com/terraform-providers/terraform-provider-ignition/releases

Done!
