### ISSUE TITLE
enable flag is no longer supported in 1.0.0

### ISSUE THREAD

**Issue by sstarcher** [terraform-providers/terraform-provider-ignition#17]
### Terraform Version
`Terraform v0.10.4`

### Affected Resource(s)
- ignition_systemd_unit

### Terraform Configuration Files
```hcl
data "ignition_systemd_unit" "init" {
  name    = "init.service"
  enable  = false
  content = "stuff"
}
```

### Debug Output
https://gist.github.com/sstarcher/7ea0004e67ecc4a98c8849a809dcc9b6

### Expected Behavior
What should have happened? The enable flag should work.

### Actual Behavior
What actually happened? The enable flag does not work.

### Steps to Reproduce
1. `terraform plan`

**Comment by sstarcher** [comment]
enable is deprecated in the ignition schema so the proper path for users is to change it to `enabled`.

Users can also
```provider "ignition" {
   version = "< 1.0.0"
}```

**Comment by mwthink** [comment]
I happened to notice this just a bit ago when my project failed on init.

Made a pull request with the documentation updated.
