### ISSUE TITLE
ignition_file: filesystem marked optional in docs but is required

### ISSUE THREAD

**Issue by discordianfish** [terraform-providers/terraform-provider-ignition#19]
Hi

docs say it's optional: https://www.terraform.io/docs/providers/ignition/d/file.html#filesystem

But it's not:
```
* module.do-fra1-test.data.ignition_file.hostname: "filesystem": required field is not set
```

Also not documented what to set this to if you don't want/need to (re)configure the rootfs.
I've already tried root which seems to work. I'd suggest making that the default if not omitted.

**Comment by omarabid** [comment]
This still shows up as optional to me? https://www.terraform.io/docs/providers/ignition/d/file.html
