### ISSUE TITLE
Ignition config should be marshaled as compact JSON

### ISSUE THREAD

**Issue by maikzumstrull** [terraform-providers/terraform-provider-ignition#2]
It's currently using indented JSON:
https://github.com/terraform-providers/terraform-provider-ignition/blob/master/ignition/resource_ignition_config.go#L122

This doesn't really help with readability, as Terraform logs the JSON blob with additional escaping, ruining the effect, plus raw Ignition configs aren't meant to be human-readable anyway. It does blow up the file size, though, and most cloud providers have a pretty tight size limit on metadata.

**Comment by adidenko** [comment]
Regression:
https://github.com/terraform-providers/terraform-provider-ignition/blob/v1.0.0/ignition/resource_ignition_config.go#L132
