### ISSUE TITLE
Invalid JSON when upgrading from 1.1.0 to 1.2.0

### ISSUE THREAD

**Issue by dstockton** [terraform-providers/terraform-provider-ignition#62]
```
Error: Error refreshing state: 1 error occurred:
	* data.ignition_config.xxx_ignition: 1 error occurred:
	* : data.ignition_config.xxx_ignition: No valid JSON found, make sure you're using .rendered and not .id: invalid character 'c' after top-level value
```

**Comment by seh** [comment]
This is due to #56 changing the schema, such that aggregates no longer refer to the composed pieces by ID, but rather as JSON fragments. In short, as the error message says, any place you were referring to the "id" attribute of an Ignition data source, refer instead to its "rendered" attribute.

**Comment by dstockton** [comment]
I am already referring by rendered :(

**Comment by seh** [comment]
Ah, well, in that case, perhaps you can share a few fragments of your configuration so that we can help diagnose what's now going wrong. It looks like we're winding up trying to consume invalid JSON, so maybe we're feeding the wrong value in the wrong place.

**Comment by dstockton** [comment]
This was my misunderstanding... because the error was referencing this resource...
```
resource "google_compute_instance_template" "foo" {
  ...
  metadata {
    user-data = "${data.ignition_config.foo_ignition.rendered}"
  }
  ...
}
```

but actually the problem is with the definition of the `foo_ignition` resource itself 🤦‍♂.
I just tried it and it works fine with 1.2. Thanks for your replies & patience!!
