### ISSUE TITLE
Ignition config spec v2.1.0 is now considered stable

### ISSUE THREAD

**Issue by maikzumstrull** [terraform-providers/terraform-provider-ignition#8]
https://coreos.com/ignition/docs/latest/configuration-v2_1.html

New features:
- Downloads can come from S3 and TFTP
- Partitions can be referenced by GUID
- Additional file systems and swap devices can be created
- Directories and symlinks can be created

Changes:
- Filesystem create block is deprecated, new `wipeFilesystem` option instead
- systemd unit option renamed from `enable` to `enabled` for consistency

Once an Ignition version that supports this format reaches CoreOS Container Linux "stable", the provider should be updated to create v2.1 configs.

**Comment by mcuadros** [comment]
Yep, is already in my mine, I am doing it ASAP

**Comment by alvelcom** [comment]
Can I help somehow with this? Not having `wipeFilesystem` is a real blocker for us.

**Comment by s-urbaniak** [comment]
@mcuadros also 👍 from my side, offering any help necessary. S3 support is also a blocker from our side.

/cc @alexsomesan @sym3tri

**Comment by mcuadros** [comment]
Finally I had time to finish the implementation https://github.com/terraform-providers/terraform-provider-ignition/pull/13
